### ISSUE TITLE
Can't register using Github directly it shows empty user data

### ISSUE THREAD

**Issue by prakashchoudhary07** [DevopediaOrg/webapp#293] opened 2018-10-20 17:42 UTC

**Comment by arvindpdmn** [comment] 2018-10-29 08:32
Could you provide more details for us to debug? 
- Before the attempted login, were you already logged into GitHub on that browser?
- Did you get a form to complete your details during the account creation process?

**Comment by arvindpdmn** [comment] 2018-10-29 09:21
I can confirm that there's a problem with "Edit Your Profile" page. It reloads even when user has submitted the form. However, when the form reloads, your account will get created if you go menu and click GitHub logo. Will work on a fix.

If you're problem is something different, please share details.

**Comment by arvindpdmn** [comment] 2018-10-29 15:53
Fixed.

**Comment by prakashchoudhary07** [comment] 2018-10-29 17:00
when I click on GitHub in login prompt the page loads and I "Empty user data". It doesn't even open GitHub login page.

**Comment by arvindpdmn** [comment] 2018-10-30 06:45
Unable to reproduce this for now. Whieh browser are you using? Try clearing cache first.

**Comment by arvindpdmn** [comment] 2019-05-04 16:23
Problem seen again in v0.22.0. Needs further investigation.

**Comment by arvindpdmn** [comment] 2019-05-06 14:14
Bug fixed and will be part of next release. Due to user having not configured a name. Quick fix is for user to configure a name in their GitHub account.

**Closed as completed by arvindpdmn** 2019-05-06 14:14 UTC
Labels: bug
